# Generated by Django 5.1.3 on 2024-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='year',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
