# Generated by Django 5.1.3 on 2024-12-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20210902_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersignup',
            name='profile_picture',
        ),
    ]
