# Generated by Django 5.1.3 on 2024-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_remove_customersignup_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
